spring.application.name=demo

# ???????? ??? ????????? (??? ??????????)
management.endpoints.web.exposure.include=*

# ????????? ??????????? health checks
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

# ????????? ??????????
info.app.name=My Spring Boot App
info.app.version=1.0.0